---
# simple example of minimal local playbook
# run with "ansible-playbook test.yml"
- name: 'Test'
  hosts: 127.0.0.1
  connection: local
  become: no
  gather_facts: True
  tasks:
  - name: make list
    set_fact:
      my_list:
        - "one"
        - "two"
      my_list2:
        - "value"

  - name: merge lists
    set_fact:
      merged_lists: "{{ my_list + my_list2 }}"

  - name: print vars
    debug: var=merged_lists

  - name: Check if a file exists
    stat:
      path: /tmp/file_does_not_exist
    register: stat_check
    tags: always

  - name: print vars
    debug: var=stat_check