---
# example war file from https://tomcat.apache.org/tomcat-8.0-doc/appdev/sample/
- name: "Deploy {{ tomcat_war_file }} tomcat webapp"
  copy:
    src: "{{ tomcat_war_file }}"
    dest: "{{ tomcat_catalina_base }}/webapps/{{ tomcat_war_file }}"
    owner: tomcat
    group: tomcat
  notify: restart_tomcat

- name: "Add users to tomcat-users.xml"
  tomcat_users:
    username: "tomcat"
    password: "{{ tomcat_password }}"
    roles:
      - "tomcat"
      - "testrole"
      - "manager-gui"
  # Hide password from logs
  no_log: true
  notify: restart_tomcat

- name: "Copy over tomcat manager context.xml"
  copy:
    src: "manager_context.xml"
    dest: "/opt/tomcat/webapps/manager/META-INF/context.xml"
  notify: restart_tomcat
